routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\paymentcontroller;
use App\Http\Controllers\frontendcontroller;
use App\Http\Controllers\admin\ticketscontroller;
use App\Http\Controllers\admin\flightscontroller;
use App\Http\Controllers\admin\usercontroller;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});
Route::group(['middleware' => ['auth']], function () {
Route::post('/payment', [paymentcontroller::class, 'payment']);
Route::get('/result', [frontendcontroller::class, 'result']);
Route::get('/Booking', [frontendcontroller::class, 'Traveller']);

Route::post('/buy', [paymentcontroller::class, 'buy']);
});
Route::get('/result', [frontendcontroller::class, 'result']);
Route::get('/profile', [frontendcontroller::class, 'profile']);
Auth::routes();
Route::group(['middleware' => ['admin']], function () {
Route::get('admin', function () {
    return view('admin/index');
});
Route::get('/admin/dashboard', [ticketscontroller::class, 'dashboard']);
Route::resource('/admin/tickets', ticketscontroller::class);
Route::resource('/admin/flights', flightscontroller::class);
Route::resource('/admin/users', usercontroller::class);
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Cashier\Billable;
use App\Http\Controllers\admin\usercontroller;

class User extends Authenticatable
{
    use Notifiable,Billable;

    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
        public function isRole()
    {
        return $this->role;
    }
}

app/Http/Controllers/admin/usercontroller.php
<?php

namespace App\Http\Controllers\admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\User;

class usercontroller extends Controller
{
    public function edit($id)
    {
        $users = User::find($id);
        return view('admin.users.edit', compact('users'));
    }
    public function update(Request $request, $id)
    {
        $user = User::find($id);
        $user->name = $request->name;
        $user->email = $request->email;
        $user->role = $request->role;
        $user->password = bcrypt($request->password);
        $user->save();

       return redirect()->back();
}
public function store(Request $request)
    {
        $user = new User;
        $user->name = $request->name;
        $user->email = $request->email;
        $user->role = $request->role;
        $user->password = bcrypt($request->password);
        $user->save();

       return redirect('/admin/users');
}
public function destroy(Request $request, $id)
    {
        $user = User::find($id);
        $user->delete();
       return redirect()->back();
}
public function index()
    {
        $users =User::all();

       return view('admin.users.index', compact('users'));
}
public function show($id)
{
    $user = User::find($id);
    return view('admin.users.show', compact('user'));
}
public function create()
{   $user = new User;
    return view('admin.users.create', compact('user'));
}
}

resources/views/admin/users/create.blade.php
@include('admin.partials.header')


<style>
    .Form
    {
    max-width: 500px;
    border: 1px solid #fff;
    margin: 40px auto 0;
    justify-content: center;
    }
</style>

      <div class="container-fluid">
        <h1 class="mt-4">
            <div class="Form2">
                <div class="form-content">
                     <form class="Form" action='/admin/users'method="post">
        @csrf

                   <center><label style="color:#fff;font-size:16px;">name</b>
                    <input type="text" name="name" class="form-control"required>

                        <label style="color:#fff;font-size:16px;">email</label>
                        <input type="text"name="email" class="form-control select-date"required>


                        <label style="color:#fff;font-size:16px;">role</label>
                        <input type="text" name="role" class="form-control select-date"required>


                        <label style="color:#fff;font-size:16px;">Password</label>
                        <input type="Password" name="password" class="form-control select-date"required>



                         <br>
                         <button style="color: #fff" class="btn btn-primary btn4 hotel"type="submit">submit</button>
                        </center>


                    </form>
                </div>
                </div>
        </h1>
      </div>
    </div>
    <!-- /#page-content-wrapper -->

  </div>
  <!-- /#wrapper -->

  <!-- Bootstrap core JavaScript -->

  <!-- Menu Toggle Script -->
  <script>
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });
  </script>



        @include('partials.jslinks')

resources/views/admin/users/edit.blade.php
@include('admin.partials.header')

<br>

<style>
    .Form
    {
    max-width: 500px;
    border: 1px solid #fff;
    margin: 40px auto 0;
    justify-content: center;
    }
</style>

      <div class="container-fluid">
            <form class="Form" action="{{ route('users.update',$users->id) }}" method="POST"enctype='multipart/form-data'>
                @csrf
                @method('PUT')
                <div class="contain">
                           <center><label style="color:#fff;">name</b>
                            <input type="text" name="name" class="form-control"value="{{$users->name}}"required>

                                <label style="color:#fff;">email</label>
                                <input type="text"name="email" class="form-control select-date"value="{{$users->email}}"required>


                                <label style="color:#fff;">role</label>
                                <input type="text"name="role" class="form-control select-date"value="{{$users->role}}"required>

                                 <br>
                                 <button style="color: #fff" class="btn btn-primary btn4 hotel"type="submit">submit</button>

                                </div></center>
                            </form>
      </div>




  <script>
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });
  </script>



        @include('partials.jslinks')

resources/views/admin/users/index.blade.php
@include('admin.partials.header')

<br>


<table class="table table-striped table-dark">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">name</th>
      <th scope="col">email</th>
      <th scope="col">role</th>

    </tr>
  </thead>
  <tbody>
  <?php foreach($users as $user){ ?>
    <tr>
      <th scope="row">{{$user->id}}</th>
      <td>{{$user->name}}</td>
      <td>{{$user->email}}</td>
      <td>{{$user->role}}</td>
      <td><a href='<?php echo "users/".$user->id."/edit" ?>' class="btn btn-info mr-2">edit</a>
        <form action=<?php echo '"users/'.$user['id'].'"';?> method="POST" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="delete">
                                    </form>
                                    </td>

    </tr>
  <?php } ?>
  </tbody>
</table>
<a class="btn btn-primary float-left ml-5"href="users/create">create</a>
  </div>


  <!-- /#wrapper -->

  <!-- Bootstrap core JavaScript -->

  <!-- Menu Toggle Script -->
  <script>
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });
  </script>



        @include('partials.jslinks')